db:
  mysql:
    host:
    port:
    name:
    user:
    pass:

spring:
  datasource:
    url: jdbc:mysql://${db.mysql.host}:${db.mysql.port}/${db.mysql.name}?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: ${db.mysql.user}
    password: ${db.mysql.pass}
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 3000
      idleTimeout: 10000
      maxLifetime: 30000
  jackson:
    serialization:
      indent_output: true
